Require Export tlc.semantics.assertion.
Require Export tlc.semantics.environment.
Require Export tlc.semantics.equivalents.
Require Export tlc.semantics.error.
Require Export tlc.semantics.lower.
Require Export tlc.semantics.pattern.
Require Export tlc.semantics.predicate.
Require Export tlc.semantics.push.
Require Export tlc.semantics.restrict.
Require Export tlc.semantics.term.
